### REGISTER
POST http://127.0.0.1:8000/api/user/register
Content-Type: application/json

{
    "name" : "Tuan",
    "email" : "tuanle@gmail.com",
    "password" : "12345678"
}

### LOGIN
POST http://127.0.0.1:8000/api/user/login
Content-Type: application/json

{
    "email" : "binhkio@gmail.com",
    "password" : "12345678"
}

###
GET http://127.0.0.1:8000/api/user/info
Content-Type: application/json

{
    "token" : "ujURkesEYE83dM3rxUn4v0ZWg3wGPCO8syUqBJJOk3oaA7exbwuwF5PQxVjQVGO4YrQzcwNtud1LbeneJq7UDpwKXgykxuPyAEikU1WuZOnNCBBHTVe712zNJxRK2y28"
}